config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  resources :accessaries
  resources :peripherals
  resources :systems
  resources :moniters
  resources :employees
  devise_for :admins

   root 'accessaries#new'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :emp_id, :name, :email_id, :mobile_no, :designation, presence: true
  has_one :moniter
  has_one :system
  belongs_to :accessary
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_id, :name, :email_id, :mobile_no, :designation)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :empid_id , :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :emp_id, :class =>"form-control" %> <br>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :name, :class =>"form-control" %>  <br> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email_id, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :email_id, :class =>"form-control" %>  <br>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mobile_no, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.number_field :mobile_no, :class =>"form-control" %>  <br>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :designation, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :designation, :class =>"form-control" %>  <br>
    </div>
  </div>
  <div class="actions">
    <%= f.submit'Save', :class =>"btn btn-success btnnew btnalign" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>Editing Employee</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Show', @employee, :class =>"btn btn-success btnnew" %> 
    <%= link_to 'Back', employees_path, :class =>"btn btn-info btnback" %>
  </div>
</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row mt">
  <div class="col-md-8 tblalign">
    <div class="content-panel panel-primary">
      <table class="table table-striped table-advance table-hover">
        <h4>Listing Employees</h4>
        <hr>
        <thead>
          <tr>
            <th>EmpId</th>
            <th>Name</th>
            <th>Email id</th>
            <th>Mobile Number</th>
            <th>Designation</th>
            <th>Actiion</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.emp_id %></td>
            <td><%= employee.name %></td>
            <td><%= employee.email_id %></td>
            <td><%= employee.mobile_no %></td>
            <td><%= employee.designation %></td>
            <td><%= link_to '', edit_employee_path(employee), :class =>"btn btn-primary btn-xs fa fa-pencil" %>
              <%= link_to '', employee, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-danger btn-xs fa fa-trash-o" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Employee', new_employee_path,:class =>"btn btnnew btn-success"%>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>NEW EMPLOYEE</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Cancel', new_accessary_path, :class =>"btn btn-danger btnnew" %>
    <%= link_to 'List', employees_path, :class =>"btn btn-primary btnnew" %>
  </div>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p style="font-size:16px"> <%= @employee.name %> </p>
        </div>
      </div>
    </div><br>
    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">EmpId </label>
      <%= @employee.emp_id %>
    </p><br>

    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">Email</label>
      <%= @employee.email_id %>
    </p><br>

    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">Mobile No</label>
      <%= @employee.mobile_no %>
    </p><br>

    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">Designation</label>
      <%= @employee.designation %>
    </p><br>

    <%= link_to 'Ok',new_accessary_path, :class =>"btn btn-theme btnnew" %>
  </div>
</div>