config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  resources :accessaries
  resources :peripherals
  resources :systems
  resources :moniters
  resources :employees
  devise_for :admins

   root 'accessaries#new'

end

app/models/peripheral.rb
class Peripheral < ActiveRecord::Base
  has_many :accessaries, :through => :accessory_peripherals
  has_many :accessory_peripherals, :dependent => :destroy
  validates :name, presence: true
end

app/controllers/peripherals_controller.rb
class PeripheralsController < ApplicationController
  before_action :set_peripheral, only: [:show, :edit, :update, :destroy]

  # GET /peripherals
  # GET /peripherals.json
  def index
    @peripherals = Peripheral.all
  end

  # GET /peripherals/1
  # GET /peripherals/1.json
  def show
  end

  # GET /peripherals/new
  def new
    @peripheral = Peripheral.new
  end

  # GET /peripherals/1/edit
  def edit
  end

  # POST /peripherals
  # POST /peripherals.json
  def create
    @peripheral = Peripheral.new(peripheral_params)

    respond_to do |format|
      if @peripheral.save
        format.html { redirect_to @peripheral, notice: 'Peripheral was successfully created.' }
        format.json { render :show, status: :created, location: @peripheral }
      else
        format.html { render :new }
        format.json { render json: @peripheral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peripherals/1
  # PATCH/PUT /peripherals/1.json
  def update
    respond_to do |format|
      if @peripheral.update(peripheral_params)
        format.html { redirect_to @peripheral, notice: 'Peripheral was successfully updated.' }
        format.json { render :show, status: :ok, location: @peripheral }
      else
        format.html { render :edit }
        format.json { render json: @peripheral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peripherals/1
  # DELETE /peripherals/1.json
  def destroy
    @peripheral.destroy
    respond_to do |format|
      format.html { redirect_to peripherals_url, notice: 'Peripheral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peripheral
      @peripheral = Peripheral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peripheral_params
      params.require(:peripheral).permit(:name)
    end
end

app/helpers/peripherals_helper.rb
module PeripheralsHelper
end

app/views/peripherals/_form.html.erb
<%= form_for(@peripheral) do |f| %>
  <% if @peripheral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peripheral.errors.count, "error") %> prohibited this peripheral from being saved:</h2>

      <ul>
      <% @peripheral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :name, :class =>"form-control" %> <br>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class =>"btn btn-success btnnew btnalign" %>
  </div>
<% end %>

app/views/peripherals/edit.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>Editing Peripheral</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Show', @peripheral, :class =>"btn btn-success btnnew" %> 
    <%= link_to 'Back', peripherals_path, :class =>"btn btn-info btnnew" %>
  </div>
</div>

app/views/peripherals/index.html.erb
<p id="notice" class="flash-message"><%= notice %></p>
<div class="row mt">
  <div class="col-md-6 tblalign">
    <div class="content-panel panel-primary">
      <table class="table table-striped table-advance table-hover">
        <h4>Listing Peripherals</h4>
        <hr>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="2">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @peripherals.each do |peripheral| %>
          <tr>
            <td><%= peripheral.name %></td>
            <td><%= link_to '',  edit_peripheral_path(peripheral), :class =>"btn btn-primary btn-xs fa fa-pencil" %></td>
            <td><%= link_to '', peripheral, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-danger btn-xs fa fa-trash-o" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Moniter', new_peripheral_path,:class =>"btn btnnew btn-success" %>
    </div>
  </div>
</div>

app/views/peripherals/new.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>New Peripheral</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Cancel', new_accessary_path, :class =>"btn btn-danger btnnew" %>
    <%= link_to 'List', peripherals_path, :class =>"btn btn-primary btnnew" %>
  </div>
</div>

app/views/peripherals/show.html.erb
<p id="notice" class="flash-message"><%= notice %></p>
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p style="font-size:16px"> Peripheral </p>
        </div>
      </div>
    </div><br>
    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">Name </label>
      <%= @peripheral.name %>
    </p><br>
   <%= link_to 'Ok',new_accessary_path, :class =>"btn btn-theme btnnew" %>
  </div>
</div>