config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  resources :accessaries
  resources :peripherals
  resources :systems
  resources :moniters
  resources :employees
  devise_for :admins

   root 'accessaries#new'

end

app/models/moniter.rb
class Moniter < ActiveRecord::Base
  validates :screen, presence: true
end

app/controllers/moniters_controller.rb
class MonitersController < ApplicationController
  before_action :set_moniter, only: [:show, :edit, :update, :destroy]

  # GET /moniters
  # GET /moniters.json
  def index
    @moniters = Moniter.all
  end

  # GET /moniters/1
  # GET /moniters/1.json
  def show
  end

  # GET /moniters/new
  def new
    @moniter = Moniter.new
  end

  # GET /moniters/1/edit
  def edit
  end

  # POST /moniters
  # POST /moniters.json
  def create
    @moniter = Moniter.new(moniter_params)

    respond_to do |format|
      if @moniter.save
        format.html { redirect_to @moniter, notice: 'Monitor was successfully Saved.' }
        format.json { render :show, status: :created, location: @moniter }
      else
        format.html { render :new }
        format.json { render json: @moniter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moniters/1
  # PATCH/PUT /moniters/1.json
  def update
    respond_to do |format|
      if @moniter.update(moniter_params)
        format.html { redirect_to @moniter, notice: 'Moniter was successfully updated.' }
        format.json { render :show, status: :ok, location: @moniter }
      else
        format.html { render :edit }
        format.json { render json: @moniter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moniters/1
  # DELETE /moniters/1.json
  def destroy
    @moniter.destroy
    respond_to do |format|
      format.html { redirect_to moniters_url, notice: 'Moniter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moniter
      @moniter = Moniter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moniter_params
      params.require(:moniter).permit(:screen)
    end
end

app/helpers/moniters_helper.rb
module MonitersHelper
end

app/views/moniters/_form.html.erb
<%= form_for(@moniter) do |f| %>
  <% if @moniter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moniter.errors.count, "error") %> prohibited this moniter from being saved:</h2>
      <ul>
      <% @moniter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :screen, :class => "col-sm-2 col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :screen, :class =>"form-control" %> <br>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class =>"btn btn-success btnnew btnalign" %>
  </div>
<% end %>

app/views/moniters/edit.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>Editing Moniter</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Show', @moniter, :class =>"btn btn-success btnnew" %> 
    <%= link_to 'Back', moniters_path, :class =>"btn btn-info btnnew" %>
  </div>
</div>

app/views/moniters/index.html.erb
<p id="notice" class="flash-message"><%= notice %></p>
<div class="row mt">
<div class="col-md-6 tblalign">
    <div class="content-panel panel-primary">
      <table class="table table-striped table-advance table-hover">
        <h4>Listing Moniters</h4>
        <hr>
        <thead>
          <tr>
            <th>Screen</th>
            <th colspan="2">Action</th>
          </tr>
        </thead>

        <tbody>
          <% @moniters.each do |moniter| %>
          <tr>
            <td><%= moniter.screen %></td>
            <td><%= link_to '', edit_moniter_path(moniter), :class =>"btn btn-primary btn-xs fa fa-pencil" %></td>
            <td><%= link_to '', moniter, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-danger btn-xs fa fa-trash-o" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Moniter', new_moniter_path,:class =>"btn btnnew btn-success" %>
    </div>
  </div>
</div>

app/views/moniters/new.html.erb
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p>New Monitor</p>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= link_to 'Cancel', new_accessary_path, :class =>"btn btn-danger btnnew" %>
    <%= link_to 'List', moniters_path, :class =>"btn btn-primary btnnew" %>
  </div>
</div>

app/views/moniters/show.html.erb
<p id="notice" class="flash-message"><%= notice %></p>
<div class="col-lg-6 col-md-4 col-sm-4 mb">
  <div class="weather-2 pn">
    <div class="weather-2-header">
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <p style="font-size:16px"> Monitor Screen </p>
        </div>
      </div>
    </div><br>
    <p>
      <label class="col-sm-2 col-sm-2 control-label emplbl">Screen </label>
      <%= @moniter.screen %>
    </p><br>
   <%= link_to 'Ok',new_accessary_path, :class =>"btn btn-theme btnnew" %>
  </div>
</div>