config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  resources :accessaries
  resources :peripherals
  resources :systems
  resources :moniters
  resources :employees
  devise_for :admins

   root 'accessaries#new'

end

app/views/layouts/_footer.html.erb
<!-- <footer class="site-footer ">
  <div class="text-center">
    2015 - Desk Accessory App
  </div>
</footer> -->

app/views/layouts/_header.html.erb
<% if signed_in? %>
<header class="header black-bg">
  <a href="" class="logo"><b>Desk Accessory App</b></a>
  <div class="top-menu">
    <ul class="nav pull-right top-menu">
      <li>
        <%= link_to "logout", destroy_admin_session_path, :method => :delete, :class =>"logout"%>
      </li>
    </ul>
  </div>
</header>
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <ul class="sidebar-menu" id="nav-accordion">
      <li class="sub-menu">
        <%= link_to "Accessory",new_accessary_path %>
      </li>
      <li class="sub-menu">
        <%= link_to "List EmpAccessory",dashboards_path %>
      </li>
      <li class="sub-menu ">
        <%= link_to "Monitor",new_moniter_path %>
      </li>
      <li class="sub-menu">
        <%= link_to "System",new_system_path %>
      </li>
      <li class="sub-menu">
        <%= link_to "Employees",new_employee_path %>
      </li>
       <li class="sub-menu">
        <%= link_to "Peripherals",new_peripheral_path %>
      </li>
    </ul>
  </div>
</aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
  <title>DeskAccessoryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="container" >
    <%= render 'layouts/header'%>
    <section id="main-content">
      <section class="wrapper">
        <%= yield %>
      </section>
    </section>
    <%= render 'layouts/footer' %>
  </section>
</body>
</html>